### ISSUE TITLE
Provide a user setting for displaying side-by-side

### ISSUE THREAD

**Issue by pitaj** [NodeBB/nodebb-plugin-composer-default#96]
Store a setting in `localStorage` for if the user wants the composer to display in a split window style instead of as a drawer at the bottom. The setting, if true, would set a new class on the html element.

Could use these CSS overrides:

```css
@media (min-width: 992px) {
    .composing body {
        width: 50vw;
        padding-bottom: 0 !important;
    }

    .composing .composer, .composing .composer.resizable {
        top: 51px !important;
        left: 50vw;
        overflow: hidden;
        box-shadow: none;
        border-left: 1px solid #eee;
        padding-top: 15px;
    }

    .composing #panel .container {
        width: 100%;
    }

    .composing .composer .resizer {
        display: none;
    }

    .composing .composer .write-preview-container {
        flex-direction: column;
    }

    .composing .composer .preview-container {
        max-width: none;
        margin-top: 15px;
    }
}
```
